### ISSUE TITLE
数据结构的建议

### ISSUE THREAD

**Issue by heineiuo** [fex-team/kityminder-core#11]
现在的数据结构是树壮的，好处是存储父子节点关系很方便，但是有以下问题：
1. 当处理大量数据（测试数据是6000个节点）时，初次加载非常慢
2. 初次加载无法定位到某个节点（这可能是我没仔细读源码，没找到API或命令，（API文档是不是该完善下了））

所以我希望改变数据结构，改用扁平化结构，父子关系通过`id:id`对的形式去实现
另外开放初次加载时显示指定节点的方法（通过id）

**Comment by zhangbobell** [comment]
建议很赞，非常感谢：
1. 树状结构还有一些限制：做图状的脑图（带游离节点和连线的脑图）的时候不方便。因为我们正在开发自由节点和自由连线，所以数据结构是需要考虑的，扁平化的思路是不错的。
2. 定位到某个节点的命令是 `minder.execCommand('camera', node);`，在 [wiki](https://github.com/fex-team/kityminder-core/wiki) 里面有部分命令。同时文档的确需要更新了。。:)

感谢建议。

**Comment by heineiuo** [comment]
@zhangbobell 感谢回复:)
