### ISSUE TITLE
在chrome下无法复制

### ISSUE THREAD

**Issue by cpoopc** [fex-team/kityminder-core#12]
kityminder-core在Firefox下可以使用快捷键Ctrl+c/Ctrl+v复制黏贴,
但是在chrome下就不行

**Comment by zhangbobell** [comment]
你说的是二次开发还是 http://naotu.baidu.com 上边的情况？目前 naotu.baidu.com 上面 chrome 已经支持 ctrl + c/v 跨 tab 页粘贴复制了。

**Comment by cpoopc** [comment]
二次开发,就是core这个基础库复制有问题.
后来我基于kityminder-editor开发就可以了

**Comment by zhangbobell** [comment]
core 的复制是自己模拟实现的，不支持跨 tab 粘贴复制的。
