### ISSUE TITLE
请问节点文本编辑功能要自己实现吗？

### ISSUE THREAD

**Issue by zhaopeifei** [fex-team/kityminder-core#15]
我把这个项目运行起来后，并没有出现编辑节点文本input标签。是因为在这个项目中，默认没有触发输入文本功能吗？另外，我找到了input的标签，也找到了更改文字内容的方法--text。我如果要实现文本输入功能，在现有的基础上，怎么实现快一些呢？非常感谢~

**Comment by zhangbobell** [comment]
kityminder-core 只包含最基本的输入，直接双击节点。更全的节点编辑功能请使用 [kityminder-editor](http://github.com/fex-team/kityminder-editor)

**Comment by zhaopeifei** [comment]
直接双击节点并没有反应呀。双击节点的话，应该显示的是一个input吧？但是双击后input标签并没有显示出来。而且按照设计的逻辑，添加节点的时候应该也要显示这个输入的input标签吧？但是在我测试时，是直接添加了一个为空的节点。

**Comment by zhangbobell** [comment]
ooo，我忘记了，是的，kityminder-core 不包含输入功能，需要自己实现。kityminder-editor 是有的。

**Comment by zhaopeifei** [comment]
哦，那我去参考一下kityminder-editor的设计吧，谢谢啦~
