### ISSUE TITLE
我弹出报错，，报错信息如下 

### ISSUE THREAD

**Issue by kangshifu1** [fex-team/kityminder-core#27]
错误
 {"data":"","status":500,"config": ,"cached":false},"statusText":"Internal Server Error"}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经解决，了解详情请点击 https://tieba.baidu.com/p/5275768151。
