### ISSUE TITLE
是否支持动态加载子节点？

### ISSUE THREAD

**Issue by TinyJiang** [fex-team/kityminder-core#3]
hi
请问一下支持动态加载子节点吗？比如说在节点配置中loadChildren:function(){...}

**Comment by techird** [comment]
您好，可以试试：

``` js
km.execCommand('appendChildNode', nodeText);
```

**Comment by TinyJiang** [comment]
sorry.
我意思没表达准确，我的意思是
1、在某个节点children没有数据的时候可以控制其只显示一个+号（默认现在是没有+号，为叶子节点）
2、点击加号的时候触发expand事件，再事件中我会去加载子节点信息
3、加载完之后appendchild

后面两步expand事件和appendchild我知道，
就是想知道第一步是否有方法可以控制没有子节点信息的时候父节点呈现收缩状态，显示+号，等待用户点击触发expand事件

**Comment by techird** [comment]
您好，

目前不支持这种方式。但是可以变通执行，比如挂载一个标记子节点，点击加号的时候再重新创建子节点。

谢谢！

Baidu FEX | 刘家鸣 | 010-59929892 | Hi: techird

发件人: Tiny Jiang <notifications@github.com<mailto:notifications@github.com>>
答复: fex-team/kityminder-core <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: Friday, March 20, 2015 at 23:29
至: fex-team/kityminder-core <kityminder-core@noreply.github.com<mailto:kityminder-core@noreply.github.com>>
抄送: Techird Liu <liujiaming@baidu.com<mailto:liujiaming@baidu.com>>
主题: Re: [kityminder-core] 是否支持动态加载子节点？ (#3)

sorry.
我意思没表达准确，我的意思是
1、在某个节点children没有数据的时候可以控制其只显示一个+号（默认现在是没有+号，为叶子节点）
2、点击加号的时候触发expand事件，再事件中我会去加载子节点信息
3、加载完之后appendchild

后面两步expand事件和appendchild我知道，
就是想知道第一步是否有方法可以控制没有子节点信息的时候父节点呈现收缩状态，显示+号，等待用户点击触发expand事件

**Comment by TinyJiang** [comment]
嗯。这个方法应该可行的。
谢谢！
