### ISSUE TITLE
请问百度脑图有客户端吗？

### ISSUE THREAD

**Issue by yangyiRunning** [fex-team/kityminder-core#34]
因为单纯WEB端有时候阅读不太方便，是否有App端或者PC，MAC端？

另附issues：
1.WEB端在导出PDF，打开后内容为一片空白。
2.另存为文件后只是保存了当下屏幕的文件内容（类似截图），挺不方便的，请问有什么办法解决？

**Comment by zhangbobell** [comment]
目前还没有客户端，
1. 目前 web 端没有提供导出为 pdf 的功能；
2. 另存为只保存了部分，请问导出的是什么格式？
