### ISSUE TITLE
将dev.html作为iframe嵌入到页面中后点击某个元素会导致父页面滚动到顶部

### ISSUE THREAD

**Issue by blurHY** [fex-team/kityminder-core#43]
如题，将dev.html作为iframe嵌入到页面中后点击某个元素会导致父页面滚动到顶部
（将其中test.html放入项目的根目录下）
[test.zip](https://github.com/fex-team/kityminder-core/files/2086860/test.zip)

**Comment by Robynebaby** [comment]
你是否设置了页面的height高度是在实例化kityminder之前呢？
