### ISSUE TITLE
怎么在vue中使用啊

### ISSUE THREAD

**Issue by zwmmm** [fex-team/kityminder-core#49]
看了一圈文档 都不知道怎么把数据展示出来

**Comment by Robynebaby** [comment]
请问你知道该怎么做了吗？我也面临同样疑惑

**Comment by zwmmm** [comment]
> 请问你知道该怎么做了吗？我也面临同样疑惑

我放弃了

**Comment by xxxzc** [comment]
npm/yarn 安装 kity 和 kityminder-core，import 后就可以用了:
```
// eslint-disable-next-line
this.km = new kityminder.Minder({
        renderTo: '#minder-container'
    });
this.km.importJson(jsonFile);
```

**Comment by jiangtao** [comment]
我写了个简单版本的 https://github.com/hexyun/vue-minder

**Comment by chengqinngling** [comment]
建议查看此项目 https://github.com/CNliushuang/vue-fs

**Comment by haihai0000003** [comment]
> npm / yarn安装kity和kityminder-core，进口后就可以用了：
> 
> ```
> // eslint-disable-next-line
> this.km = new kityminder.Minder({
>         renderTo: '#minder-container'
>     });
> this.km.importJson(jsonFile);
> ```

您好,小白想请教一下,这两个包都有好几M大小,到时候vue项目build的时候会有什么影响吗
