### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by hohogpb** [fex-team/kityminder-core#7]
1，节点图片支持base64的image: "data:image/png;base64,iVBORw0KGg。。。。"
![qq 20151021091811](https://cloud.githubusercontent.com/assets/6960725/10625320/8fa03d28-77d4-11e5-970f-43fbeeb00d74.png)

2，导入数据时候增加原生json（非字符串json，就算是map吧）的支持，测试时发现小数据貌似是可以的，但数据大了就不行了
![qq 20151021091710](https://cloud.githubusercontent.com/assets/6960725/10625306/6d2d641e-77d4-11e5-8043-e99f10ec5f75.png)

**Comment by zhangbobell** [comment]
1. kityminder-core 的 image 已经支持了插入 base64 编码的图片，可以通过命令的形式插入。但是绝大多数人习惯的方式可能是图片链接，所以在 kityminder-editor 的插入图片的功能只提供了插入图片链接的功能；
2. protocol 下的 json.js 已经是原生的 json 导入了，如果想插入 string 类型的导入，在函数执行前通过 JSON.parse() 转换即可。

**Comment by hohogpb** [comment]
ok  谢谢，响应速度很给力~  ！
